### ISSUE TITLE
Test motor control interrupts

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pay#26]
I think I forgot to call `sei()` to enable interrupts in the motor library. At some point, we should test whether we can receive faults from the motor driver.

**Comment by LornaLan** [comment]
can confirm that sei( ) is not called for motors. Will test that with the calibration test.

**Comment by LornaLan** [comment]
The motor interrupt pin is not connected properly (through PEX and PEX interrupts instead of directly to MCU), not sure if this still applies. Will update code as error polling probably.
