### ISSUE TITLE
Verification of heater tests and documentation

### ISSUE THREAD

**Issue by LornaLan** [HeronMkII/pay#27]
Full functional thermistor test with 5 heaters, 10 thermistors for verification of PAY-SSM. Please document all the progress here. Things need to be tested:

- Whether all connections of heaters on the PCB are properly functioning/to the correct desinated heater
- The voltage readings for each heaters and thermistors are as expected
- Look into the default case of thermistors.c (maybe 0.0 is okay)

**Comment by BrytniR** [comment]
On the actual pay pcb board, Thermistors 1, 6, and 2 correspond to THM 1, 2, 3 on the pay-ssm pcb diagram
