### ISSUE TITLE
Test PAY-SSM with actuation plate distance sensors

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pay#30]
We need to test the distance sensors with the PCB itself. We need a formula/algorithm for converting the ADC input voltage to a distance. If a formula is not accurate enough, we might want to use a lookup table (similar to the thermistors), by storing a bunch of known points and doing a linear approximation between them.

**Comment by LornaLan** [comment]
Working on that from now on, will write the LED and phototransistor code first, giving the voltage reading from the channel. May include conversion function later.
