### ISSUE TITLE
Implement ADC test for PAY-SSM v4 PCB

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pay#48]
Create a new `manual_tests/adc_test` that reads all 12 channels on both ADCs (ADC1 and ADC2), printing their descriptions, raw values, and converted values (with units). Also need to update the constants in `src/devices.h` for the new board.

**Comment by Tahreeem** [comment]
commit 77b4b9e52f41df39b636ec929793b627ba0944ce addresses this

**Comment by LornaLan** [comment]
Thank you Tahreem for doing this! I am going to upload this test to PAY-SSM v4 soon. Will let you know if anything worth noting comes up.
