### ISSUE TITLE
Bring up harness tests

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pay#49]

**Comment by LornaLan** [comment]
I am going to create a new branch for pay-ssm v4 bringup tests. Not sure if doing this with harness or just manual test formats, will decide soon. Basically the steps for an entire bringup procedure are:
enable 10V boost and 6V boost
ADC readings (thank you @Tahreeem, will merge the branch `adc_testing` after uploading test)
environmental sensor readings (this should be minimal change from before)

After the above are done, we can move on to something more complicated:
heaters control (@mlin331 is working on this)
motors control
interface with pay-optical
CAN communication

**Comment by brunofalmeida** [comment]
If you're ever unsure about how to test something I recommend just going with a manual test, then you might choose to migrate it to a harness test later if it makes sense.
