### ISSUE TITLE
Flight model diagnostic

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pay#56]
Conceptually the same thing as for EPS (https://github.com/HeronMkII/eps/issues/35), but for the PAY data/actions.

**Comment by LornaLan** [comment]
@YongDaLi Work in progress, have some small issues needing correction right now
- current reading after enabling heaters are off
- current reading on 10V is off
(by off we mean comparing to the reading on the power supply)

**Comment by brunofalmeida** [comment]
I fixed a few of the issues and merged to have an almost-complete version, but there are still a few problems you need to work through.
